<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Misd\PhoneNumberBundle\MisdPhoneNumberBundle::class => ['all' => true],
    Broadway\Bundle\BroadwayBundle\BroadwayBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    A2lix\AutoFormBundle\A2lixAutoFormBundle::class => ['all' => true],
    A2lix\TranslationFormBundle\A2lixTranslationFormBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],
    Gesdinet\JWTRefreshTokenBundle\GesdinetJWTRefreshTokenBundle::class => ['all' => true],
    Knp\DoctrineBehaviors\DoctrineBehaviorsBundle::class => ['all' => true],
    Knp\Bundle\GaufretteBundle\KnpGaufretteBundle::class => ['all' => true],
    Nelmio\ApiDocBundle\NelmioApiDocBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    OpenLoyalty\Bundle\AnalyticsBundle\OpenLoyaltyAnalyticsBundle::class => ['all' => true],
    OpenLoyalty\Bundle\AuditBundle\OpenLoyaltyAuditBundle::class => ['all' => true],
    OpenLoyalty\Bundle\CampaignBundle\OpenLoyaltyCampaignBundle::class => ['all' => true],
    OpenLoyalty\Bundle\CoreBundle\OpenLoyaltyCoreBundle::class => ['all' => true],
    OpenLoyalty\Bundle\EarningRuleBundle\OpenLoyaltyEarningRuleBundle::class => ['all' => true],
    OpenLoyalty\Bundle\EmailBundle\OpenLoyaltyEmailBundle::class => ['all' => true],
    OpenLoyalty\Bundle\EmailSettingsBundle\OpenLoyaltyEmailSettingsBundle::class => ['all' => true],
    OpenLoyalty\Bundle\ImportBundle\OpenLoyaltyImportBundle::class => ['all' => true],
    OpenLoyalty\Bundle\LevelBundle\OpenLoyaltyLevelBundle::class => ['all' => true],
    OpenLoyalty\Bundle\MarkDownBundle\OpenLoyaltyMarkDownBundle::class => ['all' => true],
    OpenLoyalty\Bundle\PaginationBundle\OpenLoyaltyPaginationBundle::class => ['all' => true],
    OpenLoyalty\Bundle\PointsBundle\OpenLoyaltyPointsBundle::class => ['all' => true],
    OpenLoyalty\Bundle\PosBundle\OpenLoyaltyPosBundle::class => ['all' => true],
    OpenLoyalty\Bundle\SegmentBundle\OpenLoyaltySegmentBundle::class => ['all' => true],
    OpenLoyalty\Bundle\SettingsBundle\OpenLoyaltySettingsBundle::class => ['all' => true],
    OpenLoyalty\Bundle\TransactionBundle\OpenLoyaltyTransactionBundle::class => ['all' => true],
    OpenLoyalty\Bundle\TranslationBundle\OpenLoyaltyTranslationBundle::class => ['all' => true],
    OpenLoyalty\Bundle\UserBundle\OpenLoyaltyUserBundle::class => ['all' => true],
    OpenLoyalty\Bundle\UtilityBundle\OpenLoyaltyUtilityBundle::class => ['all' => true],
    OpenLoyalty\Bundle\WorldTextBundle\OpenLoyaltyWorldTextBundle::class => ['all' => true],
];
